# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: milosz
      POSTGRES_USERNAME: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  jhapp:
    build: .
    restart: always
    ports:
      - 8081:8080
  web:
    build:
      context: justhappened-web/.
      dockerfile: Dockerfile
      depends_on:
        - db
        - jhapp
  caddy:
    image: caddy
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - 80:80
      - 443:443
    command: caddy reverse-proxy --from miloszlewandowski.pl --to jhapp:8080

volumes:
  caddy_data:
  caddy_config:
  pgdata: