version: '3.7'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
    - pgdata:/var/lib/postgresql/data2

  app:
    image: openjdk:17-alpine
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - "./target/miloszlewandowski-0.2.4.jar:/app/app.jar"
    command: java -jar /app/app.jar
    depends_on:
      - db
    environment:
      SPRING_APPLICATION_JSON: '{"spring.datasource.url":"jdbc:postgresql://db:5432/postgres"}'

volumes:
  pgdata:
