drop table if exists activities CASCADE
drop table if exists emotions CASCADE
drop table if exists moodchecks CASCADE
drop table if exists necessities CASCADE
drop table if exists observation CASCADE
drop table if exists patients CASCADE
drop table if exists patients_activities CASCADE
drop table if exists patients_the_records CASCADE
drop table if exists records CASCADE
drop table if exists records_emotions CASCADE
drop table if exists therapists CASCADE
drop table if exists threads CASCADE
drop table if exists threads_the_records CASCADE
create table activities (activity_id integer generated by default as identity, activity_name varchar(255), patient_id integer, primary key (activity_id))
create table emotions (emotion_id integer generated by default as identity, name varchar(255), primary key (emotion_id))
create table moodchecks (moodcheck_id integer generated by default as identity, mood integer, self_esteem integer, activity_activity_id integer, the_record_record_id integer, primary key (moodcheck_id))
create table necessities (id integer generated by default as identity, fulfill_level varchar(255), importance integer, name varchar(255), primary key (id))
create table observation (observation_id integer generated by default as identity, effect varchar(255), situation varchar(255), thought varchar(255), thread_id integer, primary key (observation_id))
create table patients (id integer generated by default as identity, name varchar(255), therapist_id integer, primary key (id))
create table patients_activities (patient_id integer not null, activities_activity_id integer not null)
create table patients_the_records (patient_id integer not null, the_records_record_id integer not null)
create table records (record_id integer generated by default as identity, date_time timestamp, moodcheck_moodcheck_id integer, observation_observation_id integer, patient_id integer, primary key (record_id))
create table records_emotions (the_record_record_id integer not null, emotions_emotion_id integer not null)
create table therapists (id integer generated by default as identity, name varchar(255), primary key (id))
create table threads (id integer generated by default as identity, name varchar(255), primary key (id))
create table threads_the_records (patients_thread_id integer not null, the_records_record_id integer not null)
alter table patients_activities add constraint UK_k0p3u0eur3bmnnqdqc7budbbb unique (activities_activity_id)
alter table patients_the_records add constraint UK_4jm7axden3e5xqbgn57t4wgc8 unique (the_records_record_id)
alter table records_emotions add constraint UK_j54xnebc8w5qwnrddma31vdbo unique (emotions_emotion_id)
alter table threads_the_records add constraint UK_c04rxmrvjemlxosxb8rmw5sp0 unique (the_records_record_id)
alter table activities add constraint FKnqt5g6pyb9q8wwptpmcw1fxo9 foreign key (patient_id) references patients
alter table moodchecks add constraint FK5x7i2ufn1a21igidls8pjr7et foreign key (activity_activity_id) references activities
alter table moodchecks add constraint FKpj5sw8x4969ai0fod7d7kvwq4 foreign key (the_record_record_id) references records
alter table observation add constraint FKpexhq60gipyywf4ru1wj24hqq foreign key (thread_id) references threads
alter table patients add constraint FK9rjk2g384s1d9vew2er5lneij foreign key (therapist_id) references therapists
alter table patients_activities add constraint FKkmoihva5s2od2xrnyxn2p3rrx foreign key (activities_activity_id) references activities
alter table patients_activities add constraint FK84krs15wnmc3y6s0e25wqeje5 foreign key (patient_id) references patients
alter table patients_the_records add constraint FK39qwgj2ibuklh78uhianshf3v foreign key (the_records_record_id) references records
alter table patients_the_records add constraint FK8ffrrkaaj4yryeetwya21ortk foreign key (patient_id) references patients
alter table records add constraint FKmyhgmt8p3ugdldvftfnqqy555 foreign key (moodcheck_moodcheck_id) references moodchecks
alter table records add constraint FKk3q6jw1r08wy7e5nuvdc2llmf foreign key (observation_observation_id) references observation
alter table records add constraint FKbdvrpwk00i0bqhq7ev1h7w3by foreign key (patient_id) references patients
alter table records_emotions add constraint FK2lslg75kt7q5eqt8jt37poe0q foreign key (emotions_emotion_id) references emotions
alter table records_emotions add constraint FKfttjvo3m53ycvhw2b9wkfgmib foreign key (the_record_record_id) references records
alter table threads_the_records add constraint FKhu2qt33eex99ope56xlbskoi2 foreign key (the_records_record_id) references records
alter table threads_the_records add constraint FKicv7u20ar0k7ukvx080pfw12e foreign key (patients_thread_id) references threads